### ISSUE TITLE
fails to load with ccl on linux

### ISSUE THREAD

**Issue by vrx** [bohonghuang/cl-glib#1]
Bound is not *, a INTEGER or a list of a INTEGER: -18446744073709551615/18446744073709551616
   [Condition of type SIMPLE-ERROR]

Restarts:
 0: [RETRY-COMPILE-FILE] Retry compiling #P"~/.roswell/local-projects/bohonghuang/cl-glib/glib/package.lisp"

**Comment by vrx** [comment]
apparently coming from package.lisp

(cl:defun put-object (object)
  (bt:with-lock-held (*objects-lock*)
    (cl:loop
       :with object-id :of-type unsigned-word := 0
       :do (cl:setf object-id (cl:random +1+maxsizet+))
       :while (cl:gethash object-id *objects*)
       :finally
          (cl:setf (cl:gethash object-id *objects*) object)
          (cl:return object-id))))

**Comment by bohonghuang** [comment]
Fixed in 9e52827cce1cbb3962536b6a5e628febab593f57
